<a href="https://colab.research.google.com/github/ash030889/Python_visu._ML_practice/blob/main/practice3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
arr = np.array([12,13]) #creating array
print(arr)

[12 13]


In [3]:
arr.dtype  # type of array

dtype('int64')

In [4]:
arr.ndim  # type of dimention

1

In [5]:
arr1 = np.array([[1,2,3],[4,5,6]])  #creating array

In [6]:
arr1.ndim    # type of dimention

2

In [7]:
arr1[1][1]  #slicing of array.

5

In [8]:
# add the array
a = np.array([10,14,15])
b = np.array([40,15,16])
print(a+b)

[50 29 31]


In [9]:
#change the data type.
arr1.astype('S')

array([[b'1', b'2', b'3'],
       [b'4', b'5', b'6']], dtype='|S21')

In [10]:
#using view
c  = arr1.view()
c[1][1] = 50
print(c)
print(arr1)

[[ 1  2  3]
 [ 4 50  6]]
[[ 1  2  3]
 [ 4 50  6]]


In [11]:
#using copy
d = arr1.copy()
d[1][2] = 60
print(d)
print(arr1)

[[ 1  2  3]
 [ 4 50 60]]
[[ 1  2  3]
 [ 4 50  6]]


In [12]:
ar = np.array([10,12,14,16,15,18,19,20])
print(ar)

[10 12 14 16 15 18 19 20]


In [13]:
#shape
ar.shape

(8,)

In [14]:
# reshape the array
ar.reshape(2,4)

array([[10, 12, 14, 16],
       [15, 18, 19, 20]])

In [15]:
ar.reshape(4,2)

array([[10, 12],
       [14, 16],
       [15, 18],
       [19, 20]])

In [18]:
#using loop and nested array.
for x in arr1:
  for y in x:
    print(y)

1
2
3
4
50
6


In [21]:
arr1.sort()
print(arr1)

[[ 1  2  3]
 [ 4  6 50]]
